Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/karchive': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kglobalaccel': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kpackage': 'Frameworks/6.24'
    # kparts for examples
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/ksvg': 'Frameworks/6.24'
    'plasma/plasma-activities': '@same'

Options:
 cppcheck-ignore-files: ['templates/']
 require-passing-tests-on: ['@all']
 cmake-options: -DBUILD_EXAMPLES=ON
