{
    "KPlugin": {
        "Authors": [
            {
                "Email": "kde-artists@kde.org",
                "Name": "KDE Visual Design Group",
                "Name[ar]": "مجموعة التصميم المرئي لكِيدِي",
                "Name[az]": "KDE Vizual Dizayn Qrupu",
                "Name[be]": "Суполка візуальнага дызайну KDE",
                "Name[ca@valencia]": "Grup de disseny visual de KDE",
                "Name[ca]": "Grup de disseny visual de KDE",
                "Name[cs]": "Skupina vizuálního návrhu KDE",
                "Name[eo]": "KDE Vida Dezajna Grupo",
                "Name[es]": "El grupo de diseño visual de KDE",
                "Name[eu]": "KDE Diseinu bisualeko taldea",
                "Name[fi]": "KDE:n visuaalinen suunnitteluryhmä",
                "Name[fr]": "Groupe de conception graphique de KDE « VDG » (Visual Design Group)",
                "Name[gl]": "Grupo de deseño visual de KDE",
                "Name[ia]": "KDE Visual Design Group (Gruppo de Designo Visual de KDE)",
                "Name[id]": "Grup Desain Visual KDE",
                "Name[ko]": "KDE 시각 디자인 그룹",
                "Name[nl]": "KDE Visuele ontwerpgroep",
                "Name[pl]": "Grupa oprawy graficznej KDE",
                "Name[pt]": "Grupo de Desenho Visual do KDE",
                "Name[pt_BR]": "Grupo de design visual do KDE (KDE VDG)",
                "Name[ru]": "Группа KDE Visual Design",
                "Name[sl]": "Skupina vizualnega designa KDE",
                "Name[sv]": "KDE:s visuella designgrupp",
                "Name[tr]": "KDE Görsel Tasarım Grubu",
                "Name[uk]": "Група з візуального дизайну KDE",
                "Name[vi]": "Đội Thiết kế Trực quan KDE",
                "Name[x-test]": "xxKDE Visual Design Groupxx",
                "Name[zh_CN]": "KDE 视觉设计团队",
                "Name[zh_TW]": "KDE VDG 視覺設計組"
            }
        ],
        "Category": "",
        "Description": "Breeze by the KDE VDG",
        "Description[ar]": "نسيم من مجموعة تصميم كِيدِي",
        "Description[az]": "KDE VDG tərəfindən Breeze İş mühiti görünüşü",
        "Description[be]": "Breeze ад KDE VDG",
        "Description[bg]": "Breeze от KDE VDG",
        "Description[ca@valencia]": "Brisa, creat pel VDG de KDE",
        "Description[ca]": "Brisa, creat pel VDG del KDE",
        "Description[cs]": "Breeze od KDE VDG",
        "Description[de]": "Breeze von der KDE VDG",
        "Description[eo]": "Brizo de la KDE VDG",
        "Description[es]": "Brisa, por KDE VDG",
        "Description[eu]": "Brisa KDEren VDGk egina",
        "Description[fi]": "Breeze KDE VDG:ltä",
        "Description[fr]": "Breeze par l'équipe « KDE VDG »",
        "Description[gl]": "Brisa do KDE VDG.",
        "Description[ia]": "Breeze (Brisa) per le KDE VDG",
        "Description[id]": "Breeze oleh KDE VDG",
        "Description[it]": "Brezza a cura del KDE VDG",
        "Description[ka]": "Breeze KDE VDG-სგან",
        "Description[ko]": "KDE 시각 디자인 그룹에서 제작한 Breeze",
        "Description[nl]": "Breeze door de KDE VDG",
        "Description[nn]": "Breeze frå KDE VDG",
        "Description[pl]": "Bryza autorstwa KDE VDG",
        "Description[pt]": "Brisa da VDG do KDE",
        "Description[pt_BR]": "Breeze pelo KDE VDG",
        "Description[ro]": "Briză, de KDE VDG",
        "Description[ru]": "Оформление рабочей среды Breeze от KDE VDG",
        "Description[sl]": "Sapica od KDE VDG",
        "Description[sv]": "Breeze av KDE:s visuella designgrupp",
        "Description[tr]": "KDE VDG tarafından Esinti",
        "Description[uk]": "Breeze, автори — KDE VDG",
        "Description[vi]": "Breeze, do KDE VDG",
        "Description[x-test]": "xxBreeze by the KDE VDGxx",
        "Description[zh_CN]": "Breeze 微风主题，由 KDE VDG (视觉设计团队) 设计制作",
        "Description[zh_TW]": "由 KDE VDG 設計的 Breeze",
        "EnabledByDefault": true,
        "Id": "default",
        "License": "LGPL",
        "Name": "Breeze",
        "Name[ar]": "نسيم",
        "Name[ca@valencia]": "Brisa",
        "Name[ca]": "Brisa",
        "Name[eo]": "Vento",
        "Name[es]": "Brisa",
        "Name[eu]": "Brisa",
        "Name[gl]": "Brisa",
        "Name[ia]": "Brisa",
        "Name[it]": "Brezza",
        "Name[ka]": "ნიავი",
        "Name[pl]": "Bryza",
        "Name[pt]": "Brisa",
        "Name[ro]": "Briză",
        "Name[sl]": "Sapica",
        "Name[tr]": "Esinti",
        "Name[x-test]": "xxBreezexx",
        "Name[zh_CN]": "Breeze 微风",
        "Version": "@KF_VERSION@",
        "Website": "https://plasma.kde.org"
    },
    "X-Plasma-API": "5.0"
}
